const techManufacturers = [
  'ABS Computer Technologies (Parent: Newegg)',
  'Acer',
  'AG Neovo',
  'Alphabet Inc.',
  'Google',
  'Amiga, Inc.',
  'ACube Systems Srl',
  'Hyperion Entertainment',
  'Aigo',
  'AMD (Advanced Micro Devices)',
  'Aleutia',
  'Alienware (Parent: Dell)',
  'AMAX Information Technologies',
  'AOpen',
  'Apple',
  'ASRock',
  'Asus',
  'AVADirect',
  'AXIOO International',
  'BenQ',
  'Biostar',
  'Brother Industries',
  'Burroughs Corporation',
  'Corona Data Systems',
  'Chassis Plans',
  'Chip PC',
  'Cisco Systems',
  'Clevo',
  'Crystal Group',
  'Compal',
  'Cooler Master',
  'CyberPowerPC',
  'Dai-Tech',
  'Data General',
  'Dell',
  'Wyse Technology',
  'DFI',
  'Digital Storm',
  'Elitegroup Computer Systems (ECS)',
  'Eagle Computer',
  'Epson',
  'Evans & Sutherland',
  'Everex',
  'EVGA',
  'Falcon Northwest',
  'FIC',
  'Fujitsu',
  'Foxconn',
  'Founder Technology',
  'Gigabyte',
  'Aorus',
  'GoPro',
  'Gradiente',
  'Groupe Bull',
  'Grundig (Parent: Arçelik)',
  'Hasee',
  'HCL',
  'Hewlett Packard Enterprise',
  'Cray',
  'Silicon Graphics International',
  'HP Inc. (formerly Hewlett-Packard)',
  'Fortify Software',
  'HP Autonomy',
  'Compaq',
  'Digital Equipment Corporation',
  'Hisense',
  'Hitachi',
  'HTC',
  'Huawei',
  'Hyundai',
  'IBM',
  'Intel',
  'Inventec',
  'Itautec',
  'IGEL',
  'Jetta International',
  'Kohjinsha',
  'Kontron AG',
  'Lanix',
  'Lanner Electronics',
  'LanSlide Gaming PCs',
  'Lenovo',
  'Medion',
  'LG',
  'LiteOn',
  'Maingear',
  'Meebox',
  'Mesh Computers',
  'Microsoft',
  'Micro-Star International (MSI)',
  'Micro Center',
  'Myria',
  'MiTAC',
  'Motion Computing',
  'Monel',
  'Motorola',
  'NComputing',
  'NCR',
  'NEC',
  'Nvidia',
  'NZXT',
  'Olidata',
  'Oracle',
  'Origin PC',
  'Panasonic',
  'Positivo Informática',
  'Puget Systems',
  'Quanta Computer',
  'RCA',
  'Razer',
  'Samsung',
  'Sapphire Technology',
  'Shuttle',
  'Síragon',
  'Sony',
  'Supermicro',
  'SupernovaGaming',
  'Systemax',
  'System76',
  'T-Platforms',
  'TabletKiosk',
  'Tadpole Computer',
  'Tatung',
  'Toshiba',
  'Tyan',
  'Unisys',
  'V3 Gaming PC',
  'Vaio',
  'Velocity Micro',
  'Vestel',
  'VIA Technologies',
  'ViewSonic',
  'Viglen',
  'Vizio',
  'Valve',
  'Walton Group',
  'Wistron',
  'Wortmann',
  'Xiaomi',
  'Zelybron',
  'Zoostorm',
  'Zotac',
  'zSpace',
];

module.exports = techManufacturers;
